#!/bin/bash
# chkconfig: 2345 20 80
# description:

. /etc/init.d/functions

script_path="/usr/sbin"
script_name="inotify-cho.sh"
id_path="/tmp"
id_name="inotify-cho.sh.pid"
log_path="/var/log/inotify-cho"
log_stdout="inotify-cho.log"
log_stderr="inotify-cho.err"

start() {
    if [ -e $id_path/$id_name ]; then
        echo $script_name is running, pid=$(cat $id_path/$id_name)
    else
        echo "Starting service.."
        echo "$(date) - Starting service.." >> $log_path/$log_stdout
        nohup $script_path/$script_name 1>> $log_path/$log_stdout 2>> $log_path/$log_stderr &
        echo $!>$id_path/$id_name
    fi
}

stop() {
    if [ -e $id_path/$id_name ]; then
        echo "Finishing service.."
        echo "$(date) - Finishing service.." >> $log_path/$log_stdout
        pkill -P $(cat $id_path/$id_name)
        rm $id_path/$id_name
    else
        echo $script_name is not running
        exit 1
    fi
}

status() {
    if [ -e $id_path/$id_name ]; then
        echo $script_name is running, pid=$(cat $id_path/$id_name)
    else
        echo $script_name is not running
        exit 1
    fi
}

case "$1" in
    start)
       start
       ;;
    stop)
       stop
       ;;
    restart)
       stop
       start
       ;;
    status)
       status
       ;;
    *)
       echo "Usage: $0 {start|stop|status|restart}"
esac

exit 0
